name: main
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PIPELINE STARTED"
  npm_audit:
    needs: [main]
    uses: ./.github/workflows/npm_audit.yaml
  type_check:
    needs: [npm_audit]
    uses: ./.github/workflows/type_check.yaml
  unit_test:
    needs: [type_check]
    uses: ./.github/workflows/unit_test.yaml
  e2e_test:
    needs: [unit_test]
    uses: ./.github/workflows/e2e_test.yaml
