name: main
on:
  push:
jobs:
  install:
    uses: ./.github/workflows/install.yaml
  scan:
    needs:
      - install
    uses: ./.github/workflows/scan.yaml
  test:
    needs:
      - scan
    uses: ./.github/workflows/test.yaml
  pages:
    needs:
      - test
    uses: ./.github/workflows/pages.yaml
