name: main
on: push
jobs:
  package_check:
    uses: ./.github/workflows/npm_audit.yaml
  code_scan:
    uses: ./.github/workflows/type_check.yaml
  unit_test:
    needs:
      - package_check
      - code_scan
    uses: ./.github/workflows/unit_test.yaml
  e2e_test:
    needs:
      - package_check
      - code_scan
    uses: ./.github/workflows/e2e_test.yaml
