name: main
on: [push]
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "HELLO MAIN"
  call_workflow:
    needs: [myjob]
    uses: ./.github/workflows/run.yaml
  unit_test:
    needs: [call_workflow]
    uses: ./.github/workflows/unit_test.yaml
