name: npm_audit
on:
  workflow_call:
  workflow_dispatch:
jobs:
  npm_audit:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PACKAGE VULNERABLITY CHECK STARTED"
      - uses: actions/checkout@v4.1.1
      - run: npm ci --no-audit
      - run: npm audit
