name: github_pages
on:
  workflow_call:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: false
jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/configure-pages@v5.0.0
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: './dist'
      - uses: actions/deploy-pages@v4.0.5
