name: github_pages
on:
  workflow_call:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/configure-pages@v5.0.0
      - uses: actions/jekyll-build-pages@v1.0.12
        with:
          source: ./
          destination: ./_site
      - uses: actions/upload-pages-artifact@v3.0.1
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4.0.5
