name: test
on:
  workflow_call:
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: npm ci --no-audit
      - run: npm run test:unit
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: npm ci --no-audit
      - run: npx playwright install
      - run: npx playwright install-deps
      - run: npm run build
      - run: npm run test:e2e
