name: type_check
on:
  workflow_call:
jobs:
  type_check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TYPE CHECK STARTED"
      - uses: actions/checkout@v4.1.1
      - run: npm ci --no-audit
      - run: npm run type-check
